# Generated by Django 2.2.9 on 2020-11-28 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20201129_0046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ('post__pub_date',)},
        ),
    ]
