# Generated by Django 2.2.6 on 2021-01-16 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_follow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
